# Fixed source snapshots; configuration never fetches dependencies.
set(SDL_SHARED ON CACHE BOOL "" FORCE)
set(SDL_STATIC OFF CACHE BOOL "" FORCE)
set(SDL_TEST_LIBRARY OFF CACHE BOOL "" FORCE)
set(SDL_TESTS OFF CACHE BOOL "" FORCE)
set(SDL_EXAMPLES OFF CACHE BOOL "" FORCE)
set(SDL_INSTALL OFF CACHE BOOL "" FORCE)
add_subdirectory(thirdparty/SDL3 EXCLUDE_FROM_ALL)

set(BUILD_SHARED_LIBS OFF)
foreach(prefix SDLIMAGE SDLTTF SDLMIXER)
    set(${prefix}_VENDORED ON CACHE BOOL "" FORCE)
    set(${prefix}_DEPS_SHARED OFF CACHE BOOL "" FORCE)
    set(${prefix}_SAMPLES OFF CACHE BOOL "" FORCE)
    set(${prefix}_TESTS OFF CACHE BOOL "" FORCE)
    set(${prefix}_EXAMPLES OFF CACHE BOOL "" FORCE)
    set(${prefix}_INSTALL OFF CACHE BOOL "" FORCE)
    set(${prefix}_STRICT ON CACHE BOOL "" FORCE)
endforeach()
foreach(format AVIF JXL TIF WEBP)
    set(SDLIMAGE_${format} OFF CACHE BOOL "" FORCE)
endforeach()
set(SDLIMAGE_BACKEND_STB OFF CACHE BOOL "" FORCE)
set(SDLIMAGE_BACKEND_IMAGEIO OFF CACHE BOOL "" FORCE)
set(SDLIMAGE_PNG ON CACHE BOOL "" FORCE)
set(SDLIMAGE_JPG ON CACHE BOOL "" FORCE)
set(SDLTTF_PLUTOSVG OFF CACHE BOOL "" FORCE)
set(SDLTTF_HARFBUZZ ON CACHE BOOL "" FORCE)
foreach(format FLAC_LIBFLAC GME MOD MP3_MPG123 MIDI OPUS VORBIS_VORBISFILE VORBIS_TREMOR WAVPACK)
    set(SDLMIXER_${format} OFF CACHE BOOL "" FORCE)
endforeach()
set(SDLMIXER_WAVE ON CACHE BOOL "" FORCE)
set(SDLMIXER_MP3 ON CACHE BOOL "" FORCE)
set(SDLMIXER_MP3_DRMP3 ON CACHE BOOL "" FORCE)
set(SDLMIXER_VORBIS_STB ON CACHE BOOL "" FORCE)
add_subdirectory(thirdparty/SDL3_image EXCLUDE_FROM_ALL)
add_subdirectory(thirdparty/SDL3_ttf EXCLUDE_FROM_ALL)
add_subdirectory(thirdparty/SDL3_mixer EXCLUDE_FROM_ALL)

add_library(elysia_sdl_gfx STATIC thirdparty/SDL3_gfx/SDL3_gfxPrimitives.c)
target_include_directories(elysia_sdl_gfx SYSTEM PUBLIC thirdparty/SDL3_gfx)
target_link_libraries(elysia_sdl_gfx PUBLIC SDL3::SDL3)
if(UNIX)
    target_link_libraries(elysia_sdl_gfx PRIVATE m)
endif()
set(ELYSIA_SDL_LIBRARIES SDL3::SDL3 SDL3_image::SDL3_image SDL3_ttf::SDL3_ttf SDL3_mixer::SDL3_mixer elysia_sdl_gfx)

function(elysia_copy_sdl_runtime target)
    if(WIN32)
        add_custom_command(TARGET ${target} POST_BUILD
            COMMAND ${CMAKE_COMMAND} -E copy_if_different
                $<TARGET_FILE:SDL3::SDL3> $<TARGET_FILE_DIR:${target}>)
    endif()
endfunction()
